export default {
	validator: {
		$jsonSchema: {
			bsonType: "object",
			title: "A session.",
			required: ["_id"],
			properties: {
				_id: {
					bsonType: "string",
					title: "ID generated by express-session."
				},
				"User ID": {
					bsonType: "objectId",
					title: "The user associated with the session."
				}
			},
			additionalProperties: {	bsonType: "object" }
		}
	}
}
