export default {
	validator: {
		$jsonSchema: {
			bsonType: "object",
			title: "A session.",
			required: ["_id", "data"],
			properties: {
				_id: {
					bsonType: "string",
					title: "ID generated by express-session."
				},
				data: {
					bsonType: "object",
					properties: {
						"User ID": {
							bsonType: "objectId",
							title: "The user associated with the session."
						}
					}
				}
			},
			additionalProperties: false
		}
	}
}
