export default {
	validator: {
		$jsonSchema: {
			bsonType: "object",
			description: "A session.",
			required: Array.of("_id", "data"),
			properties: {
				_id: {
					bsonType: "string",
					description: "ID generated by express-session."
				},
				data: {
					bsonType: "object",
					properties: {
						"User ID": {
							bsonType: "objectId",
							description: "The user associated with the session."
						}
					}
				}
			},
			additionalProperties: false
		}
	}
}
